/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-06-17 06:45:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/home/acura/portal/acura-apps/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/struts2-core-2.1.8.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1254480334000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.1.8.1.jar", Long.valueOf(1354067144000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-dojo-plugin-2.1.8.1.jar", Long.valueOf(1354067196000L));
    _jspx_dependants.put("jar:file:/home/acura/portal/acura-apps/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/struts2-dojo-plugin-2.1.8.1.jar!/META-INF/struts-dojo-tags.tld", Long.valueOf(1254481724000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fhead_0026_005fparseContent_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fform_0026_005fname_005fid_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005flabelSeparator_005flabel_005fkey_005fcssStyle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fhidden_0026_005fvalue_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsx_005fhead_0026_005fparseContent_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fform_0026_005fname_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005flabelSeparator_005flabel_005fkey_005fcssStyle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fvalue_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsx_005fhead_0026_005fparseContent_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fform_0026_005fname_005fid_005faction.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005flabelSeparator_005flabel_005fkey_005fcssStyle_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fvalue_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n");
      out.write("<title>Sign On</title>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\n");
      out.write("\t");
      if (_jspx_meth_sx_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body,td,th {\n");
      out.write("\tfont-size: 11pt;\n");
      out.write("\tfont-weight: 300;\n");
      out.write("\tfont-style: normal;\n");
      out.write("\tfont-family: \"Times New Roman\", Times, serif;\n");
      out.write("}\n");
      out.write("body {\n");
      out.write("\tmargin-left: 0px;\n");
      out.write("\tmargin-top: 0px;\n");
      out.write("\tmargin-right: 0px;\n");
      out.write("\tmargin-bottom: 0px;\n");
      out.write("\tbackground-image: url(file:///C|/Documents and Settings/Reshu/Desktop/images/body-bg.jpg);\n");
      out.write("\tbackground-repeat: repeat;\n");
      out.write("\tbackground-image: url();\n");
      out.write("\tbackground-color: #E9E9E9;\n");
      out.write("}\n");
      out.write("a:link {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #222942;\n");
      out.write("}\n");
      out.write("a:visited {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #222942;\n");
      out.write("}\n");
      out.write("a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("a:active {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write(".style57 {font-size: 10pt; font-weight: normal; color: #333333; font-family: Verdana, Arial, Helvetica, sans-serif; }\n");
      out.write(".style58 {font-size: 13px; font-weight: 600; color: #666666; font-family: Verdana, Arial, Helvetica, sans-serif; }\n");
      out.write(".style65 {font-size: 16px; font-weight: bold; color: #FFFFFF; font-family: Verdana, Arial, Helvetica, sans-serif; }\n");
      out.write(".style66 {font-size: 13px; font-weight: 600; color: #FFFFFF; font-family: Verdana, Arial, Helvetica, sans-serif; }\n");
      out.write(".style70 {font-size: 10pt; font-weight: bold; color: #333333; font-family: Verdana, Arial, Helvetica, sans-serif; }\n");
      out.write(".style71 {\n");
      out.write("\tcolor: #40537B;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function changeWidthHomePage(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tvar wd = parseInt(srcElement.style.width);\n");
      out.write("\t\tif (screen.width == 1024)\n");
      out.write("\t\t\tsrcElement.style.width = wd - ((screen.width/1250)*30);\n");
      out.write("\t\telse if (screen.width == 800)\n");
      out.write("\t\t\tsrcElement.style.width = wd - ((screen.width/1250)*70);\n");
      out.write("\t\telse\n");
      out.write("\t\t\tsrcElement.style.width = wd - ((screen.width/1250)*6);\n");
      out.write("\t}\n");
      out.write("\tfunction changeWidth(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tsrcElement.style.width = screen.width - ((screen.width/1250)*43);\n");
      out.write("\t}\n");
      out.write("function MM_preloadImages() { //v3.0\n");
      out.write("  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();\n");
      out.write("    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)\n");
      out.write("    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}\n");
      out.write("}\n");
      out.write("function goToLogin() \n");
      out.write("{\n");
      out.write("\tdocument.forms[\"loginPage\"].submit();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body onload=\"document.all.userId.focus();MM_preloadImages('file:///E|/acura_html/images/blue_over_but.png');\">\n");
      out.write("\n");
      out.write("<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("  <tr>\n");
      out.write("    <th align=\"center\" scope=\"col\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\n");
      out.write("      <tr>\n");
      out.write("        <th align=\"left\" valign=\"bottom\" scope=\"col\"><table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("            <tr>\n");
      out.write("              <th align=\"left\" valign=\"bottom\" scope=\"col\"><table width=\"1000\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#E9E9E9\">\n");
      out.write("                <tr>\n");
      out.write("                  <td width=\"1023\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr>\n");
      out.write("                      <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header_img1.jpg\" width=\"397\" height=\"359\" /></td>\n");
      out.write("                      <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header_img2.jpg\" width=\"626\" height=\"359\" /></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                      <td bgcolor=\"#FFFFFF\"><span class=\"style71\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contact Us Call: 020-3267 0355 , 94230 04767<br />\n");
      out.write("                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email: amol.gadre@acurasoftwares.com</span></td>\n");
      out.write("                      <td><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header2_img2.jpg\" width=\"626\" height=\"40\" /></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr>\n");
      out.write("                      <td width=\"72%\" align=\"left\" valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                        <tr>\n");
      out.write("                          <td width=\"99%\" height=\"7\"></td>\n");
      out.write("                          <td width=\"1%\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header_img4.jpg\" width=\"34\" height=\"7\" /></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td colspan=\"2\"><table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                              <td width=\"12\">&nbsp;</td>\n");
      out.write("                              <td width=\"714\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"../images/portalImage/blue_text_box_bg.jpg\">\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" background=\"../images/portalImage/box_top_bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_left_corner.png\" width=\"3\" height=\"34\" /></td>\n");
      out.write("                                  <td colspan=\"2\" align=\"center\" background=\"../images/portalImage/box_top_bg.jpg\"><span class=\"style65\">Features of our Applications </span></td>\n");
      out.write("                                  <td width=\"17\" align=\"right\" background=\"../images/portalImage/box_top_bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_right_corner.png\" width=\"4\" height=\"34\" /></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"20\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">No more waiting for support for software or hardware issues.</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">Use our online applications to conduct daily operations of your clinic, hospital or pathological lab.</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                 <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">Our applications include formats provided by doctors and healthcare experts.</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\" valign=\"top\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">Billing, Recording of Patient's Information, Surgeries, Lab Tests, Printing Invoices, Email Reports to Patients and More.</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td width=\"7\">&nbsp;</td>\n");
      out.write("                                  <td width=\"668\" align=\"left\" valign=\"middle\" class=\"style57\"> Online reports availiability for patients with lifetime free accounts for patients.</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("\n");
      out.write("                                <tr>\n");
      out.write("                                  <td width=\"17\" bgcolor=\"#FFFFFF\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_left_corner.png\" width=\"17\" height=\"19\" /></td>\n");
      out.write("                                  <td width=\"10\">&nbsp;</td>\n");
      out.write("                                  <td colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td bgcolor=\"#FFFFFF\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_right_corner.png\" width=\"17\" height=\"19\" align=\"right\" /></td>\n");
      out.write("                                </tr>\n");
      out.write("                              </table></td>\n");
      out.write("                              <td width=\"10\">&nbsp;</td>\n");
      out.write("                            </tr>\n");
      out.write("                          </table></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                         \n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                      </table>\n");
      out.write("                        </td>\n");
      out.write("                      <td align=\"left\" valign=\"top\" bgcolor=\"#FFFFFF\">\n");
      out.write("                      ");
      if (_jspx_meth_s_005fform_005f0(_jspx_page_context))
        return;
      out.write("    \n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                      <td colspan=\"2\" align=\"left\" valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                        <tr>\n");
      out.write("                          <td width=\"13\" bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td colspan=\"2\" bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td colspan=\"2\" bgcolor=\"#FFFFFF\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                              <td width=\"0%\"></td>\n");
      out.write("                              <td width=\"98%\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"../images/portalImage/blue_text_box_bg2.jpg\">\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" background=\"../images/portalImage/box_top_bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_left_corner.png\" width=\"3\" height=\"34\" /></td>\n");
      out.write("                                  <td colspan=\"2\" align=\"center\" background=\"../images/portalImage/box_top_bg.jpg\" class=\"style65\">What are we offering? </td>\n");
      out.write("                                  <td width=\"17\" align=\"right\" background=\"../images/portalImage/box_top_bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_right_corner.png\" width=\"4\" height=\"34\" /></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"center\" valign=\"top\">&nbsp;</td>\n");
      out.write("                                  <td width=\"8\">&nbsp;</td>\n");
      out.write("                                  <td width=\"938\" align=\"left\" valign=\"middle\" class=\"style58\">We are currently offering online applications on cloud based environment for:</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\" valign=\"top\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">Pathological Labs</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\" valign=\"top\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">Clinics and Hospitals</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td colspan=\"2\" align=\"right\" valign=\"top\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bullet_img1.png\" width=\"19\" height=\"22\" /></td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                  <td align=\"left\" valign=\"middle\" class=\"style57\">Gynaecological Hospitals</td>\n");
      out.write("                                  <td>&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td height=\"7\" class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td height=\"7\">&nbsp;</td>\n");
      out.write("                                  <td class=\"style57\">With applications hosted on our cloud based servers, you don't have to worry about software or hardware issues occurring on your laptop or PC to stop you from working on your applications.<br />\n");
      out.write("For any application related issue, you just need to give us a call, and we will solve your problem within no time with an able technical support team resolving your issues on the server.<br />\n");
      out.write("No more AMC or per visit cost for your software. If your PC or Laptop gives you hard time, your work won't stop. Access the online application from a different laptop or PC. </td>\n");
      out.write("                                  <td height=\"7\">&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td height=\"7\">&nbsp;</td>\n");
      out.write("                                  <td class=\"style57\">There is no installation required at your end. You pay only a mere amount of Rs. 1,000.00 on annual basis for using our applications. Your data is secure on our servers. </td>\n");
      out.write("                                  <td height=\"7\">&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                  <td class=\"style57\"></td>\n");
      out.write("                                  <td height=\"7\"></td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td height=\"7\" colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td height=\"7\">&nbsp;</td>\n");
      out.write("                                  <td class=\"style57\">If you are computerizing your clinic, hospital or lab for the first time, you do not incur any hardware cost. Just use a minimum configuration PC or latop to get the best of services.<br />\n");
      out.write("Contact us on 020-3267 0355 or 94230 04767 to book your order now</td>\n");
      out.write("                                  <td height=\"7\">&nbsp;</td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                  <td width=\"17\" bgcolor=\"#FFFFFF\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_left_corner.png\" width=\"17\" height=\"19\" align=\"left\" /></td>\n");
      out.write("                                  <td width=\"9\">&nbsp;</td>\n");
      out.write("                                  <td colspan=\"2\">&nbsp;</td>\n");
      out.write("                                  <td bgcolor=\"#FFFFFF\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_right_corner.png\" width=\"17\" height=\"19\" align=\"right\" /></td>\n");
      out.write("                                </tr>\n");
      out.write("                              </table></td>\n");
      out.write("                              <td>&nbsp;</td>\n");
      out.write("                            </tr>\n");
      out.write("                          </table></td>\n");
      out.write("                          <td height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td colspan=\"2\" bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td width=\"996\" bgcolor=\"#FFFFFF\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"../images/portalImage/blue_text_box_bg3.jpg\">\n");
      out.write("                            <tr>\n");
      out.write("                              <td width=\"17\" background=\"../images/portalImage/box_top_bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_left_corner.png\" width=\"3\" height=\"34\" /></td>\n");
      out.write("                              <td width=\"962\" align=\"center\" background=\"../images/portalImage/box_top_bg.jpg\" class=\"style65\">Subscription Plans</td>\n");
      out.write("                              <td width=\"17\" align=\"right\" background=\"../images/portalImage/box_top_bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_right_corner.png\" width=\"4\" height=\"34\" /></td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                              <td>&nbsp;</td>\n");
      out.write("                              <td><table width=\"99%\" border=\"1\" cellpadding=\"0\" cellspacing=\"1\" bordercolor=\"#66C2CF\">\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"50\" colspan=\"2\" align=\"center\" background=\"../images/portalImage/bg7.jpg\" class=\"style66\">Applications</td>\n");
      out.write("                                    <td width=\"251\" align=\"center\" background=\"../images/portalImage/bg7.jpg\" class=\"style66\">Description</td>\n");
      out.write("                                    <td align=\"center\" background=\"../images/portalImage/bg7.jpg\" class=\"style66\">Registration Charges </td>\n");
      out.write("                                    <td width=\"91\" align=\"center\" background=\"../images/portalImage/bg7.jpg\" class=\"style66\">Monthly Hosting Charges</td>\n");
      out.write("                                    <td width=\"91\" align=\"center\" background=\"../images/portalImage/bg7.jpg\" class=\"style66\">Annual Hosting Charges</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"40\" colspan=\"3\" background=\"../images/portalImage/table_bg3.jpg\">&nbsp;</td>\n");
      out.write("                                    <td width=\"104\" align=\"center\" valign=\"middle\" background=\"../images/portalImage/table_bg3.jpg\" class=\"style70\">(Rs.)</td>\n");
      out.write("                                    <td align=\"center\" background=\"../images/portalImage/table_bg3.jpg\" class=\"style70\">(Rs.)</td>\n");
      out.write("                                    <td align=\"center\" background=\"../images/portalImage/table_bg3.jpg\" class=\"style70\">(Rs.)</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  \n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"60\" colspan=\"2\" align=\"left\" valign=\"top\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/pro_lab_header_img.jpg\" width=\"304\" height=\"60\" /></td>\n");
      out.write("                                    <td background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style70\">&nbsp; Pro-Lab - A soultion for &nbsp;&nbsp;Pathological  Labs. </span></td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">3,000.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">950.00&nbsp; &nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">10,000.00&nbsp;</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"10\" colspan=\"6\" background=\"../images/portalImage/table_bg3.jpg\"></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"60\" colspan=\"2\" align=\"left\" valign=\"top\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/health-care-plus.jpg\" width=\"377\" height=\"60\" /></td>\n");
      out.write("                                    <td background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style70\">&nbsp;&nbsp;HealthCare-Plus- Software for &nbsp;&nbsp;General                                                                        Practioners \n");
      out.write("and smaller &nbsp;&nbsp;hospitals. </span></td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">2,000.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">750.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">8,000.00&nbsp;</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"10\" colspan=\"6\" background=\"../images/portalImage/table_bg3.jpg\"></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"60\" colspan=\"2\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/gynosoft_table_img.jpg\" width=\"355\" height=\"60\" />                                      </td>\n");
      out.write("                                    <td background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style70\">&nbsp;&nbsp;Gynosoft -Gynaecological <br />\n");
      out.write("&nbsp;&nbsp;Hospital Management.</span></td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">2,000.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">750.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">8,000.00&nbsp;</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"10\" colspan=\"6\" background=\"../images/portalImage/table_bg3.jpg\"></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td width=\"208\" height=\"60\" valign=\"top\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/health-care-small.jpg\" width=\"173\" height=\"60\" /></td>\n");
      out.write("                                    <td width=\"186\" valign=\"top\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/pro-lab-small.jpg\" width=\"155\" height=\"60\" align=\"right\" /></td>\n");
      out.write("                                    <td background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style57\">&nbsp;&nbsp;</span><span class=\"style70\">HealthCare-Plus + Pro-Lab.</span></td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style70\">4,000.00</span>&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">1,500.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">16,000.00&nbsp;</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                   <td height=\"10\" colspan=\"6\" background=\"../images/portalImage/table_bg3.jpg\"></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"60\" align=\"left\" valign=\"top\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/gynosoft-small.jpg\" width=\"173\" height=\"60\" align=\"left\" /><br />\n");
      out.write("                                        <br /></td>\n");
      out.write("                                    <td height=\"60\" valign=\"top\" background=\"../images/portalImage/table_cel_bg.jpg\" class=\"style57\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/pro-lab-small.jpg\" width=\"155\" height=\"60\" align=\"right\" /></td>\n");
      out.write("                                    <td background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style57\">&nbsp;&nbsp;</span><span class=\"style70\">Gynosoft + Pro-Lab.</span></td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">4,000.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">1,500.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">16,000.00&nbsp;</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                   <td height=\"10\" colspan=\"6\" background=\"../images/portalImage/table_bg3.jpg\"></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td height=\"60\" colspan=\"2\" align=\"left\" valign=\"top\" background=\"../images/portalImage/easy-prescription-bg.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/easy-prescription-img.jpg\" width=\"334\" height=\"60\" /></td>\n");
      out.write("                                    <td background=\"../images/portalImage/table_bg1.jpg\"><span class=\"style57\">&nbsp;&nbsp;</span><span class=\"style70\">Easy Prescription.</span></td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">1,000.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">5,00.00&nbsp;</td>\n");
      out.write("                                    <td align=\"right\" background=\"../images/portalImage/table_bg1.jpg\" class=\"style70\">5,000.00&nbsp;</td>\n");
      out.write("                                  </tr>\n");
      out.write("                              </table></td>\n");
      out.write("                              <td>&nbsp;</td>\n");
      out.write("                            </tr>\n");
      out.write("                            <tr>\n");
      out.write("                              <td bgcolor=\"#FFFFFF\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_left_corner.png\" width=\"17\" height=\"19\" /></td>\n");
      out.write("                              <td>&nbsp;</td>\n");
      out.write("                              <td bgcolor=\"#FFFFFF\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_right_corner.png\" width=\"17\" height=\"19\" /></td>\n");
      out.write("                            </tr>\n");
      out.write("                          </table></td>\n");
      out.write("                          <td align=\"right\" bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td colspan=\"2\" bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td colspan=\"2\" bgcolor=\"#FFFFFF\">&nbsp;</td>\n");
      out.write("                          <td height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                          <td colspan=\"3\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/bottom_img.png\" width=\"1023\" height=\"171\" /></td>\n");
      out.write("                          <td width=\"1\" height=\"2\" bgcolor=\"#FFFFFF\"></td>\n");
      out.write("                        </tr>\n");
      out.write("                      </table></td>\n");
      out.write("                      </tr>\n");
      out.write("                  </table></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td>&nbsp;</td>\n");
      out.write("                </tr>\n");
      out.write("              </table>\n");
      out.write("              </th>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("              <td></td>\n");
      out.write("            </tr>\n");
      out.write("        </table></th>\n");
      out.write("      </tr>\n");
      out.write("    </table></th>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tchangeWidth(document.getElementById('imageTable'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_01'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_02'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_03'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_04'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_05'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_06'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_07'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_08'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_09'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_10'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_11'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_12'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_13'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_14'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_15'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_16'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_17'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_18'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_19'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_20'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_21'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_22'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_23'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_24'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_25'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_26'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_27'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_28'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_29'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_30'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_31'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_32'));\n");
      out.write("\tchangeWidthHomePage(document.getElementById('header_img_33'));\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sx_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:head
    org.apache.struts2.dojo.views.jsp.ui.HeadTag _jspx_th_sx_005fhead_005f0 = (org.apache.struts2.dojo.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fsx_005fhead_0026_005fparseContent_005fnobody.get(org.apache.struts2.dojo.views.jsp.ui.HeadTag.class);
    _jspx_th_sx_005fhead_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sx_005fhead_005f0.setParent(null);
    // /login/login.jsp(11,1) name = parseContent type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sx_005fhead_005f0.setParseContent("true");
    int _jspx_eval_sx_005fhead_005f0 = _jspx_th_sx_005fhead_005f0.doStartTag();
    if (_jspx_th_sx_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsx_005fhead_0026_005fparseContent_005fnobody.reuse(_jspx_th_sx_005fhead_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsx_005fhead_0026_005fparseContent_005fnobody.reuse(_jspx_th_sx_005fhead_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:form
    org.apache.struts2.views.jsp.ui.FormTag _jspx_th_s_005fform_005f0 = (org.apache.struts2.views.jsp.ui.FormTag) _005fjspx_005ftagPool_005fs_005fform_0026_005fname_005fid_005faction.get(org.apache.struts2.views.jsp.ui.FormTag.class);
    _jspx_th_s_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fform_005f0.setParent(null);
    // /login/login.jsp(201,22) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setId("loginPage");
    // /login/login.jsp(201,22) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setName("loginPage");
    // /login/login.jsp(201,22) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fform_005f0.setAction("login");
    int _jspx_eval_s_005fform_005f0 = _jspx_th_s_005fform_005f0.doStartTag();
    if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fform_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("                      <table width=\"275\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
        out.write("                        <tr>\n");
        out.write("                          <td colspan=\"3\"><img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/images/portalImage/login_box_top_img.jpg\" width=\"280\" height=\"24\" align=\"right\" /></td>\n");
        out.write("                        </tr>\n");
        out.write("                        <tr>\n");
        out.write("                          <td colspan=\"3\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
        out.write("                            <tr>\n");
        out.write("                              <td width=\"1\" bgcolor=\"#EFC695\">&nbsp;</td>\n");
        out.write("                              <td><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">\n");
        out.write("                                <tr>\n");
        out.write("                                  <td width=\"11%\">&nbsp;</td>\n");
        out.write("                                  <td width=\"33%\">&nbsp;</td>\n");
        out.write("                                  <td width=\"56%\">&nbsp;</td>\n");
        out.write("                                </tr>\n");
        out.write("                                <tr>\n");
        out.write("                                \t<td style=\"text-align: center;\" colspan=\"5\">\n");
        out.write("                                \t\t<table style=\"text-align: center;\">\n");
        out.write("                                \t\t\t");
        if (_jspx_meth_s_005ftextfield_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\t\n");
        out.write("                                \t\t</table>\n");
        out.write("                                \t</td>\n");
        out.write("                                \t");
        if (_jspx_meth_s_005fhidden_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("                                </tr>\n");
        out.write("                                <tr>\n");
        out.write("                                  <td height=\"40\" align=\"center\" background=\"../images/portalImage/table_bg5.jpg\" class=\"style58\"><img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/images/portalImage/userid_img.png\" width=\"15\" height=\"16\" /></td>\n");
        out.write("                                  <td background=\"../images/portalImage/table_bg5.jpg\"><span class=\"style58\">USER ID</span></td>\n");
        out.write("                                  <td background=\"../images/portalImage/table_bg5.jpg\">\n");
        out.write("                                  <table>\n");
        out.write("                                  \t\t");
        if (_jspx_meth_s_005ftextfield_005f1(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("                                  </table>\n");
        out.write("                                  </td>\n");
        out.write("                                </tr>\n");
        out.write("                                <tr>\n");
        out.write("                                  <td>&nbsp;</td>\n");
        out.write("                                  <td>&nbsp;</td>\n");
        out.write("                                  <td>&nbsp;</td>\n");
        out.write("                                </tr>\n");
        out.write("                                <tr>\n");
        out.write("                                  <td height=\"40\" align=\"center\" background=\"../images/portalImage/table_bg5.jpg\" class=\"style58\"><img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/images/portalImage/password_img.png\" width=\"15\" height=\"9\" /></td>\n");
        out.write("                                  <td background=\"../images/portalImage/table_bg5.jpg\"><span class=\"style58\">PASSWORD</span></td>\n");
        out.write("                                  <td background=\"../images/portalImage/table_bg5.jpg\">\n");
        out.write("                                    <table>\n");
        out.write("                                  \t\t");
        if (_jspx_meth_s_005fpassword_005f0(_jspx_th_s_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("                               \t\t</table>\n");
        out.write("                                  </td>\n");
        out.write("                                </tr>\n");
        out.write("                                <tr>\n");
        out.write("                                  <td>&nbsp;</td>\n");
        out.write("                                  <td>&nbsp;</td>\n");
        out.write("                                  <td>&nbsp;</td>\n");
        out.write("                                </tr>\n");
        out.write("                                <tr>\n");
        out.write("                                  <td colspan=\"3\" align=\"center\"><a href=\"#\" onclick=\"goToLogin();\"><img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/images/portalImage/log-in_but.png\" width=\"125\" height=\"40\" /></a></td>\n");
        out.write("                                  </tr>\n");
        out.write("                              </table></td>\n");
        out.write("                              <td width=\"1\" bgcolor=\"#EFC695\">&nbsp;</td>\n");
        out.write("                            </tr>\n");
        out.write("                          </table></td>\n");
        out.write("                          </tr>\n");
        out.write("                        \n");
        out.write("                        <tr>\n");
        out.write("                          <td width=\"28\"><img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/images/portalImage/login_left_corner.png\" width=\"26\" height=\"20\" align=\"left\" /></td>\n");
        out.write("                          <td width=\"221\">&nbsp;</td>\n");
        out.write("                          <td width=\"26\"><img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/images/portalImage/login_right_corner.png\" width=\"26\" height=\"20\" align=\"right\" /></td>\n");
        out.write("                        </tr>\n");
        out.write("                      </table>\n");
        out.write("                      ");
        int evalDoAfterBody = _jspx_th_s_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fform_0026_005fname_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fform_0026_005fname_005fid_005faction.reuse(_jspx_th_s_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f0 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005flabelSeparator_005flabel_005fkey_005fcssStyle_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/login.jsp(219,35) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setKey("loginValidation");
    // /login/login.jsp(219,35) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setLabel("");
    // /login/login.jsp(219,35) name = labelSeparator type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setLabelSeparator("");
    // /login/login.jsp(219,35) name = cssStyle type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setCssStyle("visibility:hidden; height:0px;");
    // /login/login.jsp(219,35) name = size type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f0.setSize("0");
    int _jspx_eval_s_005ftextfield_005f0 = _jspx_th_s_005ftextfield_005f0.doStartTag();
    if (_jspx_th_s_005ftextfield_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005flabelSeparator_005flabel_005fkey_005fcssStyle_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005flabelSeparator_005flabel_005fkey_005fcssStyle_005fnobody.reuse(_jspx_th_s_005ftextfield_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fhidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:hidden
    org.apache.struts2.views.jsp.ui.HiddenTag _jspx_th_s_005fhidden_005f0 = (org.apache.struts2.views.jsp.ui.HiddenTag) _005fjspx_005ftagPool_005fs_005fhidden_0026_005fvalue_005fkey_005fnobody.get(org.apache.struts2.views.jsp.ui.HiddenTag.class);
    _jspx_th_s_005fhidden_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fhidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/login.jsp(222,33) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fhidden_005f0.setKey("signon");
    // /login/login.jsp(222,33) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fhidden_005f0.setValue("true");
    int _jspx_eval_s_005fhidden_005f0 = _jspx_th_s_005fhidden_005f0.doStartTag();
    if (_jspx_th_s_005fhidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fhidden_0026_005fvalue_005fkey_005fnobody.reuse(_jspx_th_s_005fhidden_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fhidden_0026_005fvalue_005fkey_005fnobody.reuse(_jspx_th_s_005fhidden_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005ftextfield_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:textfield
    org.apache.struts2.views.jsp.ui.TextFieldTag _jspx_th_s_005ftextfield_005f1 = (org.apache.struts2.views.jsp.ui.TextFieldTag) _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.get(org.apache.struts2.views.jsp.ui.TextFieldTag.class);
    _jspx_th_s_005ftextfield_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftextfield_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/login.jsp(229,36) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setKey("userId");
    // /login/login.jsp(229,36) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setLabel("");
    // /login/login.jsp(229,36) name = labelSeparator type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setLabelSeparator("");
    // /login/login.jsp(229,36) name = maxlength type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setMaxlength("20");
    // /login/login.jsp(229,36) name = size type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setSize("20");
    // /login/login.jsp(229,36) name = required type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005ftextfield_005f1.setRequired("true");
    int _jspx_eval_s_005ftextfield_005f1 = _jspx_th_s_005ftextfield_005f1.doStartTag();
    if (_jspx_th_s_005ftextfield_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftextfield_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.reuse(_jspx_th_s_005ftextfield_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:password
    org.apache.struts2.views.jsp.ui.PasswordTag _jspx_th_s_005fpassword_005f0 = (org.apache.struts2.views.jsp.ui.PasswordTag) _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.get(org.apache.struts2.views.jsp.ui.PasswordTag.class);
    _jspx_th_s_005fpassword_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fform_005f0);
    // /login/login.jsp(243,36) name = key type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setKey("password");
    // /login/login.jsp(243,36) name = label type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setLabel("");
    // /login/login.jsp(243,36) name = labelSeparator type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setLabelSeparator("");
    // /login/login.jsp(243,36) name = maxlength type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setMaxlength("20");
    // /login/login.jsp(243,36) name = size type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setSize("20");
    // /login/login.jsp(243,36) name = required type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fpassword_005f0.setRequired("true");
    int _jspx_eval_s_005fpassword_005f0 = _jspx_th_s_005fpassword_005f0.doStartTag();
    if (_jspx_th_s_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fpassword_0026_005fsize_005frequired_005fmaxlength_005flabelSeparator_005flabel_005fkey_005fnobody.reuse(_jspx_th_s_005fpassword_005f0);
    return false;
  }
}
