/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-06-17 07:19:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.portal.domain.PortalConstant;
import java.util.Date;
import com.portal.domain.Account;

public final class billingDesk_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.portal.domain.Account");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.portal.domain.PortalConstant");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta\n");
      out.write("\thttp-equiv=\"Content-Type\"\n");
      out.write("\tcontent=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Payment Result</title>\n");
      out.write("</head>\n");
      out.write("<meta\n");
      out.write("\thttp-equiv=\"Content-Type\"\n");
      out.write("\tcontent=\"text/html; charset=iso-8859-1\" />\n");
      out.write("<title>Sign On</title>\n");
      out.write("<meta\n");
      out.write("\thttp-equiv=\"Content-Type\"\n");
      out.write("\tcontent=\"text/html; charset=utf-8\" />\n");
      out.write("<meta\n");
      out.write("\thttp-equiv=\"X-UA-Compatible\"\n");
      out.write("\tcontent=\"IE=7\" />\n");
      out.write("<sx:head parseContent=\"true\" />\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body, td, th {\n");
      out.write("\tfont-size: 11pt;\n");
      out.write("\tfont-weight: 300;\n");
      out.write("\tfont-style: normal;\n");
      out.write("\tfont-family: \"Times New Roman\", Times, serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tmargin-left: 0px;\n");
      out.write("\tmargin-top: 0px;\n");
      out.write("\tmargin-right: 0px;\n");
      out.write("\tmargin-bottom: 0px;\n");
      out.write("\tbackground-image:\n");
      out.write("\t\turl(file:///C|/Documents and Settings/Reshu/Desktop/images/body-bg.jpg);\n");
      out.write("\tbackground-repeat: repeat;\n");
      out.write("\tbackground-image: url();\n");
      out.write("\tbackground-color: #E9E9E9;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:link {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #222942;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:visited {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #222942;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:hover {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:active {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".style57 {\n");
      out.write("\tfont-size: 10pt;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\tcolor: #333333;\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".style58 {\n");
      out.write("\tfont-size: 13px;\n");
      out.write("\tfont-weight: 600;\n");
      out.write("\tcolor: #666666;\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".style65 {\n");
      out.write("\tfont-size: 16px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".style66 {\n");
      out.write("\tfont-size: 13px;\n");
      out.write("\tfont-weight: 600;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".style70 {\n");
      out.write("\tfont-size: 10pt;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tcolor: #333333;\n");
      out.write("\tfont-family: Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".style71 {\n");
      out.write("\tcolor: #40537B;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction changeWidthHomePage(srcElement) {\n");
      out.write("\t\tvar wd = parseInt(srcElement.style.width);\n");
      out.write("\t\tif (screen.width == 1024)\n");
      out.write("\t\t\tsrcElement.style.width = wd - ((screen.width / 1250) * 30);\n");
      out.write("\t\telse if (screen.width == 800)\n");
      out.write("\t\t\tsrcElement.style.width = wd - ((screen.width / 1250) * 70);\n");
      out.write("\t\telse\n");
      out.write("\t\t\tsrcElement.style.width = wd - ((screen.width / 1250) * 6);\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction changeWidth(srcElement) {\n");
      out.write("\t\tsrcElement.style.width = screen.width - ((screen.width / 1250) * 43);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction MM_preloadImages() { //v3.0\n");
      out.write("\t\tvar d = document;\n");
      out.write("\t\tif (d.images) {\n");
      out.write("\t\t\tif (!d.MM_p)\n");
      out.write("\t\t\t\td.MM_p = new Array();\n");
      out.write("\t\t\tvar i, j = d.MM_p.length, a = MM_preloadImages.arguments;\n");
      out.write("\t\t\tfor (i = 0; i < a.length; i++)\n");
      out.write("\t\t\t\tif (a[i].indexOf(\"#\") != 0) {\n");
      out.write("\t\t\t\t\td.MM_p[j] = new Image;\n");
      out.write("\t\t\t\t\td.MM_p[j++].src = a[i];\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction goToLogin() {\n");
      out.write("\t\tdocument.forms[\"loginPage\"].submit();\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\tfunction changeHeight(srcElement)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tsrcElement.style.height = screen.height - 420;\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction changeWidthHomePage(srcElement)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar wd = parseInt(srcElement.style.width);\n");
      out.write("\t\t\tif (screen.width == 1024)\n");
      out.write("\t\t\t\tsrcElement.style.width = wd - ((screen.width/1250)*30);\n");
      out.write("\t\t\telse if (screen.width == 800)\n");
      out.write("\t\t\t\tsrcElement.style.width = wd - ((screen.width/1250)*70);\n");
      out.write("\t\t\telse\n");
      out.write("\t\t\t\tsrcElement.style.width = wd - ((screen.width/1250)*6);\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction changeWidth(srcElement)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tsrcElement.style.width = screen.width - ((screen.width/1250)*43);\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction changeAmount($i) {\n");
      out.write("\t\t\tvar s= document.getElementById(\"amount_id\");\n");
      out.write("\t\t\tvar cur = document.getElementById(\"currency_id\").value;\n");
      out.write("\t\t\tif($i == \"monthly\" && cur == \"inr\") {\n");
      out.write("\t\t\t\ts.value = 1000;\n");
      out.write("\t\t\t} else if($i == \"monthly\" && cur == \"usd\") {\n");
      out.write("\t\t\t\ts.value = 15.16;\n");
      out.write("\t\t\t} else if($i == \"anually\" && cur == \"inr\") {\n");
      out.write("\t\t\t\ts.value = 10000;\n");
      out.write("\t\t\t} else if($i == \"anually\" && cur == \"usd\") {\n");
      out.write("\t\t\t\ts.value = 151.64;\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ts.value = 0;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction changeAmount2($i) {\n");
      out.write("\t\t\tvar s= document.getElementById(\"amount_id\");\n");
      out.write("\t\t\tvar sub= document.getElementById(\"subscription_type\").value;\n");
      out.write("\t\t\tif($i == \"inr\" && sub == \"monthly\") {\n");
      out.write("\t\t\t\ts.value = 1000;\n");
      out.write("\t\t\t} else if($i == \"inr\" && sub == \"anually\") {\n");
      out.write("\t\t\t\ts.value = 10000;\n");
      out.write("\t\t\t} else if($i == \"usd\" && sub == \"monthly\") {\n");
      out.write("\t\t\t\ts.value = 15.16;\n");
      out.write("\t\t\t} else if($i == \"usd\" && sub == \"anually\") {\n");
      out.write("\t\t\t\ts.value = 151.64;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction MM_preloadImages() {\n");
      out.write("\t\t  var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();\n");
      out.write("\t\t    var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)\n");
      out.write("\t\t    if (a[i].indexOf(\"#\")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction validateemail()  \n");
      out.write("\t\t{  \n");
      out.write("\t\tvar x=document.billingDesk.billing_email.value;  \n");
      out.write("\t\tvar atposition=x.indexOf(\"@\");  \n");
      out.write("\t\tvar dotposition=x.lastIndexOf(\".\");  \n");
      out.write("\t\tif (atposition<1 || dotposition<atposition+2 || dotposition+2>=x.length){  \n");
      out.write("\t\t  alert(\"Please enter a valid e-mail address \\n atpostion:\"+atposition+\"\\n dotposition:\"+dotposition);  \n");
      out.write("\t\t  return false;  \n");
      out.write("\t\t  }  \n");
      out.write("\t\t}\n");
      out.write("\t\tfunction validateOtherFields() {\n");
      out.write("\t\t\tvar billing_city_var = document.billingDesk.billing_city.value;\n");
      out.write("\t\t\tvar billing_state_var = document.billingDesk.billing_state.value;\n");
      out.write("\t\t\tif(billing_city_var == null || billing_city_var == \"\") {\n");
      out.write("\t\t\t\talert(\"Please enter city name\");\n");
      out.write("\t\t\t\treturn true;\n");
      out.write("\t\t\t} else if(billing_state_var=null || billing_state_var == \"\") {\n");
      out.write("\t\t\t\talert(\"Please enter state\");\n");
      out.write("\t\t\t\treturn true;\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\treturn false;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tfunction validateForm() {\n");
      out.write("\t\t\tvar amount_var = document.billingDesk.amount.value; \n");
      out.write("\t\t    if (amount_var == null || amount_var == \"\") {\n");
      out.write("\t\t        alert(\"Please select subscription type\");\n");
      out.write("\t\t        return false;\n");
      out.write("\t\t    } else if(validateOtherFields()) {\n");
      out.write("\t\t    \t\n");
      out.write("\t\t    } else {\n");
      out.write("\t\t    \tdocument.billingDesk.closest('form').submit()\n");
      out.write("\t\t    }\n");
      out.write("\t\t}\n");
      out.write("\t\t\t\n");
      out.write("</script>\n");

		HttpSession sessionsa = request.getSession(false);
		Account ac = (Account)sessionsa.getAttribute("account");
		String userName_var = ac.getOwnerName();
		String address_var = ac.getAddress();
		String emailId_var = ac.getEmailId().toString();
		String subscriptionEndDate_var = ac.getSubscriptionEndDate().toString();
		String mobileNumber_var = ac.getMobileNumber();

      out.write("\n");
      out.write("<body>\n");
      out.write("<form style=\"\" method=\"post\" name=\"billingDesk\" action=\"customerData\" >\n");
      out.write("\t<table\n");
      out.write("\t\twidth=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<th align=\"center\" scope=\"col\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th\n");
      out.write("\t\t\t\t\t\t\talign=\"left\" valign=\"bottom\" scope=\"col\">\n");
      out.write("\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th align=\"left\" valign=\"bottom\" scope=\"col\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<table width=\"1000\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#E9E9E9\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"1023\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header_img1.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"397\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"359\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header_img2.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"626\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"359\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td bgcolor=\"#FFFFFF\"><span class=\"style71\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contact\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tUs Call: 020-3267 0355 , 94230 04767<br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email:\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tamol.gadre@sarathisoftech.com\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header2_img2.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"626\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"40\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"100%\" align=\"left\" valign=\"top\" bgcolor=\"#FFFFFF\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"99%\" height=\"7\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"1%\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/header_img4.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"34\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"7\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"12\">&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"714\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground=\"../images/portalImage/blue_text_box_bg.jpg\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolspan=\"2\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talign=\"center\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground=\"../images/portalImage/box_top_bg.jpg\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_left_corner.png\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"3\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"34\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolspan=\"2\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground=\"../images/portalImage/box_top_bg.jpg\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"style65\"> Your Subscription\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tEnded </span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"17\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talign=\"right\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground=\"../images/portalImage/box_top_bg.jpg\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/text_box_right_corner.png\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"4\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"34\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\">&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\">&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"17\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbgcolor=\"#FFFFFF\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_left_corner.png\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"17\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"19\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"10\">&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\">&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td bgcolor=\"#FFFFFF\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/portalImage/blue_text_box_right_corner.png\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twidth=\"17\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\theight=\"19\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talign=\"right\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td width=\"10\">&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("<table width=\"100%\" height=\"0\" border='1' align=\"center\" background=\"../images/portalImage/blue_text_box_bg2.jpg\" >\n");
      out.write("\t<tr align=\"center\" >\n");
      out.write("\t\t<td colspan=\"2\"><b>Compulsory information</b></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Your subscription ends on</td>\n");
      out.write("\t\t<td><input type=\"text\" disabled=\"disabled\" name=\"merchant_id\" id=\"merchant_id\" value=\"");
      out.print( ac.getSubscriptionEndDate() );
      out.write("\" readonly=\"true\" /></td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr style=\"display: none;\">\n");
      out.write("\t\t\t\t<td>TID\t:</td><td><input type=\"text\" name=\"tid\" id=\"tid\" readonly /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr style=\"display: none;\">\n");
      out.write("\t\t\t\t<td>Merchant Id</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"merchant_id\" id=\"merchant_id\" value=\"85389\" readonly=\"true\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr style=\"display: none;\">\n");
      out.write("\t\t\t\t<td>Order Id</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"order_id\" value=\"1\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr><td>Subscription Type</td>\n");
      out.write("\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t<select id=\"subscription_type\" name=\"subscription\" onchange=\"changeAmount(value)\">\n");
      out.write("\t\t\t\t\t\t<option value=\"NONE\">--- Select ---</option> \n");
      out.write("\t\t\t\t\t   <option value=\"monthly\">Monthly</option>\n");
      out.write("\t\t\t\t\t   <option value=\"anually\">Anually</option>\n");
      out.write("\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<tr><td>Currency</td>\n");
      out.write("\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t<select id=\"currency_id\" name=\"currency\" onchange=\"changeAmount2(value)\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"inr\">INR</option> \n");
      out.write("\t\t\t\t\t\t   <option value=\"usd\">USD</option>\n");
      out.write("\t\t\t\t\t\t</select> \n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<!-- <td>Currency</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"currency\" value=\"INR\" /></td> -->\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Amount</td>\n");
      out.write("\t\t\t\t<td><input id=\"amount_id\" type=\"text\" name=\"amount\" value=\"\" readonly=\"true\" required  /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr style=\"display: none;\">\n");
      out.write("\t\t\t\t<td>Redirect URL</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"redirect_url\" value= ");
      out.print(PortalConstant.REDIRECT_URL);
      out.write(" />\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr style=\"display: none;\">\n");
      out.write("\t\t\t\t<td>Cancel URL</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"cancel_url\" value= ");
      out.print(PortalConstant.REDIRECT_URL);
      out.write(" />\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr style=\"display: none;\">\n");
      out.write("\t\t\t\t<td>Language</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"language\" id=\"language\" value=\"EN\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td colspan=\"2\"><b>Billing information(optional):</b></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing Name</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_name\" value=\"");
      out.print( userName_var );
      out.write("\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing Address:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_address\" value=\"");
      out.print(address_var);
      out.write("\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing City:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_city\" value=\"\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing State:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_state\" value=\"\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing Zip:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_zip\" value=\"411041\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing Country:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_country\" value=\"India\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing Mobile Number:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_tel\" value=\"");
      out.print(mobileNumber_var);
      out.write("\" readonly=\"true\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td>Billing Email:</td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"billing_email\" value=\"");
      out.print(emailId_var);
      out.write("\"  readonly=\"true\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr align=\"center\" >\n");
      out.write("\t\t\t\t<td colspan=\"2\">\n");
      out.write("\t\t\t\t\t<a href=\"javascript:validateForm()\" onclick=\"\" role=\"button\" class=\"btn\" id=\"submit\" data-toggle=\"modal\">\n");
      out.write("\t\t\t\t\t<img src=\"../images/continue_img.png\" width=\"117\" height=\"34\" /></a>\n");
      out.write("\t\t\t\t\t <a id=\"cancel\" href=\"/portal/login/login.jsp\">\n");
      out.write("\t\t\t\t\t <img src=\"../images/cancel_img.png\" width=\"117\" height=\"34\" /></a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t<tr align=\"center\" >\n");
      out.write("\t\t\t\t<td colspan=\"2\" >\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"style1\" target=\"_blank\"\n");
      out.write("\t\t\t\t\t\tonclick=\"window.open('http://www.sarathisoftech.com','SarathiSoftechSite', 'addressbar=1,menubar=0,resizable=1,location=1,status=1,scrollbars=1,width=1300,height=900,left=0,top=0');\"\n");
      out.write("\t\t\t\t\t\ttitle=\"Gynosoft Release 1.3.15\"> <font color=\"RED\">&copy; 2015 - Sarathi Softech Pvt. Ltd. Pune</font></a>\n");
      out.write("\t\t\t\t</td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t\n");
      out.write("</table>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</table></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table></th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</table></th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table></th>\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t//changeWidthInOnlineUserHeader(document.getElementById('headerDiv'));\n");
      out.write("\tsetJmesaTableWidth('#TestRecordsByUserSearch');\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
