/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-06-17 06:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.portal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.lang.Throwable;
import org.jmesa.web.HttpServletRequestWebContext;

public final class exceptionHandler_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/home/acura/portal/acura-apps/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/struts2-core-2.1.8.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1254480334000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.1.8.1.jar", Long.valueOf(1354067144000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1354067128000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-dojo-plugin-2.1.8.1.jar", Long.valueOf(1354067196000L));
    _jspx_dependants.put("jar:file:/home/acura/portal/acura-apps/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/struts2-dojo-plugin-2.1.8.1.jar!/META-INF/struts-dojo-tags.tld", Long.valueOf(1254481724000L));
    _jspx_dependants.put("/WEB-INF/tld/jmesa.tld", Long.valueOf(1449040468000L));
    _jspx_dependants.put("jar:file:/home/acura/portal/acura-apps/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/portal/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064314020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.lang.Throwable");
    _jspx_imports_classes.add("org.jmesa.web.HttpServletRequestWebContext");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  \t<title>Unanticipated Error Condition Occurred</title>\n");
      out.write("  \t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"bodyClass\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<table class=\"mainTable\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" >\n");
      out.write("\t<tr>\n");
      out.write("       \t<td colspan=\"2\" class=\"screenHeader\" align=\"center\">\n");
      out.write("        \t<span class=\"screenHeaderSpan\">Unanticipated Error Condition Occurred</span>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("    <tr>\n");
      out.write("    \t<td style=\"text-align:center;\">\n");
      out.write("    \t\t<div class=\"fixedDiv\" id=\"outterDiv\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("            \t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td valign=\"top\">\n");
      out.write("\t            \t\t\t<table >\n");
      out.write("\t\t\t\t\t\t\t\t  \t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  \t<td style=\"text-align:center;\"><b><i>Contact  Information: </i></b></td>\n");
      out.write("\t\t\t                        <td style=\"width:92%;text-align:center;\">\n");
      out.write("\t\t\t                        <div class=\"subComponentDiv\">\n");
      out.write("\t\t\t                        \t<font color=\"black\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<u>");
      out.print( "System Error. Please contact us at Acura Softwares to resolve this error." );
      out.write("</u>\n");
      out.write("\t\t\t\t\t    \t\t\t\t<br />\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<u>");
      out.print( "Contact Name : Mr. Amol Gadre <br/> Mobile Number: 9423004767 <br/> Phone Number: 020-32670355" );
      out.write("</u>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</font>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"window.opener.logoutForm.submit(); window.close();\"><font color=\"red\"><b>Sign On Again</b></font></a>\n");
      out.write("\t\t\t                   \t    </div>\n");
      out.write("\t\t\t                   \t    </td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\n");
      out.write("                       \t\t\t\t\n");
      out.write("\t\t            \t\t\t\t\n");
      out.write("\t\t            \t\t\t\t<tr>\n");
      out.write("\t\t            \t\t\t\t<td style=\"width:8%;vetical-align:top;text-align:center;\"><b><i>Exception Information<font color=\"red\">*</font>: </i></b></td>\n");
      out.write("\t\t            \t\t\t\t<td style=\"width:92%;\">\n");
      out.write("\t\t            \t\t\t\t<div class=\"subComponentDiv\">\n");
      out.write("\t\t            \t\t\t\t<table>\n");
      out.write("\t\t            \t\t\t\t\n");
      out.write("                       \t\t\t\t <tr>\n");
      out.write("                       \t\t\t\t \t<td style=\"width:50%; text-align:center; vertical-align:top;\">\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t");

											//out.println("<!--");
											if (exception != null)
											{
												out.print("<br /><textarea readonly=\"true\" cols=\"80\" rows=\"24\">"+exception.getMessage()+ "\n" );
												StackTraceElement[] stackArray = exception.getStackTrace();
												for (StackTraceElement element : stackArray)
												{
													out.println(element.toString());
												}
												out.println("</textarea><br /><br />");
											}
											//out.println("-->");
											
      out.write("\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t        \n");
      out.write("\t\t\t\t\t\t\t  \t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t  \t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("                   \t\t\t\t</table>\n");
      out.write("                   \t\t\t\t</div>\n");
      out.write("\t            \t\t\t\t</td>\n");
      out.write("\t            \t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t    \t\t</table>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</td>\n");
      out.write("\t</tr>\n");
      out.write("\t\n");
      out.write("</table>\n");
      out.write("<script>\n");
      out.write("\tchangeWidth(document.getElementById('outterDiv'));\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
