/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2016-06-17 06:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.portal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.portal.util.GenericUtils;

public final class include_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.portal.util.GenericUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"exceptionHandler.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<style media=\"all\" type=\"text/css\">@import \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/menu_style.css\";</style>\n");
      out.write("<!-- jmesa css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/jmesa.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/example.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/calendar.css\"></link>\n");
      out.write("\n");
      out.write("<!-- blueprint framework -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bp/custom_screen.css\" type=\"text/css\" media=\"screen, projection\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bp/print.css\" type=\"text/css\" media=\"print\">\n");
      out.write("<!--[if lt IE 8]><link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bp/ie.css\" type=\"text/css\" media=\"screen, projection\"><![endif]-->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bp/fancy-type/screen.css\" type=\"text/css\" media=\"screen, projection\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/labtest-table.css\"></link>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- js files -->\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-1.3.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.jmesa.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jmesa.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.validate.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/common-utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/date-utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/time-utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/calendar.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/report.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/registerReport.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/numericValidations.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/multiselectionlist.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/patientHistory.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/login.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/global.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/hmsButtons.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cms/editableDropDown.js\"> </script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\tjavascript:window.history.forward(1);\n");
      out.write("\n");
      out.write("\tfunction changeWidth(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tvar factor = 315;\n");
      out.write("\t\tif(screen.height == 720)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tfactor = 303;\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(screen.height == 600)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tfactor = 348;\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(screen.height == 737)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tfactor = 337;\n");
      out.write("\t\t}\n");
      out.write("\t\telse if (screen.height == 768)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tfactor = 345;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*43);\n");
      out.write("\t\tsrcElement.style.height = screen.height -((screen.height/768)*factor);\n");
      out.write("\t}\n");
      out.write("\tfunction changeWidthHomePage(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*46);\n");
      out.write("\t}\n");
      out.write("\tfunction changeWidthInPopUp(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*43);\n");
      out.write("\t}\n");
      out.write("\tfunction changeWidthInSubmit(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\ttry\n");
      out.write("\t\t{\n");
      out.write("\t\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*43);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tsrcElement.style.left = ((screen.width/1024)*7);\n");
      out.write("\t\t\tsrcElement.style.top = ((screen.height/768)*630);\n");
      out.write("\t\t}\n");
      out.write("\t\tcatch(e)\n");
      out.write("\t\t{\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tfunction setJmesaTableWidth(id)\n");
      out.write("\t{\n");
      out.write("\t\tvar factor = 14;\n");
      out.write("\t\tif (screen.width == 1024)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tfactor = 20;\n");
      out.write("\t\t}\n");
      out.write("\t\tvar xfactor = screen.width - ((screen.width/1024)*43) - factor;\n");
      out.write("\t\t$(id).width(xfactor);\n");
      out.write("\t}\n");
      out.write("\tfunction setSearchFieldsDivWidth(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tvar xfactor = screen.width - ((screen.width/1024)*75);\n");
      out.write("\t\t$(srcElement).width(xfactor);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction changeHeightInViewBillingHistoryDiv(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tif(screen.height == 720)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar xfactor = screen.height - ((screen.height/768)*598);\n");
      out.write("\t\t}\n");
      out.write("\t\telse \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar xfactor = screen.height - ((screen.height/768)*573);\n");
      out.write("\t\t}\n");
      out.write("\t\t$(srcElement).height(xfactor);\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction changeHeightInViewCustomTestRestultDiv(srcElement)\n");
      out.write("\t{\n");
      out.write("\t\tif(screen.height == 720)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar xfactor = screen.height - ((screen.height/768)*598);\n");
      out.write("\t\t}\n");
      out.write("\t\telse \n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar xfactor = screen.height - ((screen.height/768)*573);\n");
      out.write("\t\t}\n");
      out.write("\t\t$(srcElement).height(xfactor);\n");
      out.write("\t}\n");
      out.write("\t  function changeWidthInOnlineUserHeader(srcElement)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar factor = 40;\n");
      out.write("\t\t\tif(screen.width == 1024)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tfactor = 39;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*factor);\n");
      out.write("\t\t\tsrcElement.style.height = screen.height - ((screen.height/768)*660);\n");
      out.write("\t\t}\n");
      out.write("\t    function changeWidthOnlineUserHeaderDiv(srcElement)\n");
      out.write("\t\t{\n");
      out.write("\t\t\ttry\n");
      out.write("\t\t\t{\n");
      out.write("\t\t    \tvar factor = 40;\n");
      out.write("\t\t\t\tif(screen.width == 1024)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tfactor = 45;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*factor);\n");
      out.write("\t\t\t} \n");
      out.write("\t\t\tcatch(e)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t    function changeWidthForJMesaOutterDiv(srcElement)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tsrcElement.style.width = screen.width - ((screen.width/1024)*43);\n");
      out.write("\t\t}\n");
      out.write("</script>\n");
      out.write("<style>            \n");
      out.write("\t#progressDiv \n");
      out.write("\t{     \n");
      out.write("\t\tvisibility: hidden;            \n");
      out.write("\t\tposition:absolute;\n");
      out.write("\t\t/*filter:alpha(opacity=40); \n");
      out.write("\t\topacity: 0.4;*/ \n");
      out.write("\t}  \n");
      out.write("\t#pleasewaitDiv \n");
      out.write("\t{     \n");
      out.write("\t\tvisibility: hidden;            \n");
      out.write("\t\tposition:absolute;\n");
      out.write("\t\tfilter:alpha(opacity=92); \n");
      out.write("\t\topacity: 0.92;\n");
      out.write("\t} \n");
      out.write("\t\t        \n");
      out.write("</style>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("<!-- \n");
      out.write("#createdBy, #lastUpdatedBy, #lastUpdatedDate, #createdDate {\n");
      out.write("background:lightgrey;\n");
      out.write("color:red;\n");
      out.write("font-weight: bold;\n");
      out.write("} \n");
      out.write("-->\n");
      out.write("</style>\n");
      out.write("<div id=\"progressDiv\">\n");
      out.write("\t<img id=\"progress\" src=\"/portal/images/Flying_envelope1.gif\" style=\"width:60 px; height: 60px; \" />\n");
      out.write("</div>\n");
      out.write("<div id=\"pleasewaitDiv\" style=\"z-index: 1\">\n");
      out.write("\t<img id=\"progress\" src=\"/portal/images/pleasewait.gif\" style=\"border: thin solid darkblue;\" />\n");
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("   var ht = screen.height/2 - 100;\n");
      out.write("   var wd = screen.width/2 - 30;\n");
      out.write("   document.getElementById('progressDiv').style.left = wd;\n");
      out.write("   document.getElementById('progressDiv').style.top = ht;\n");
      out.write("   var ht = screen.height/2 - 120;\n");
      out.write("   var wd = screen.width/2 - 100;\n");
      out.write("   document.getElementById('pleasewaitDiv').style.left = wd;\n");
      out.write("   document.getElementById('pleasewaitDiv').style.top = ht;\n");
      out.write("\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
